### ISSUE TITLE
Bug on Mobile Banner Render

### ISSUE THREAD

**Issue by bendhouseart** [openneuropet/openneuropet.github.io#3]
Per @CPernet 's description:

> the render on cell phone bugs a little for the banner bit (likely a box css issue but haven't figure it out yet)

*TODO*

Immediate step is to determine what mobile browsers are affected:

- [x] Chrome
- [x] Safari
- [ ] Firefox

**Comment by CPernet** [comment]
chrome/brave the buttons inside the banner get wrapped around -- hence my hyp. that's a CSS box definition issue 

![Screenshot_20210526_061053_com brave browser](https://user-images.githubusercontent.com/4772878/119601359-51108980-bde9-11eb-8ee2-000afabe8b22.jpg)

**Comment by bendhouseart** [comment]
Eep, I see I see.

**Comment by bendhouseart** [comment]
Confirmed on Safari

![Screen Shot 2021-05-26 at 7 03 42 PM](https://user-images.githubusercontent.com/28850131/119742193-3c69db00-be55-11eb-8271-9cc8d470d584.png)

**Comment by bendhouseart** [comment]
Well Greg's suggestion of:

```css@media(max-width: 767px){
 .Modern-Slider .text-content {
    display: flex;
    flex-direction: column;
 }
}
```

Fixed some of them, but the access tools is still buggy.

![Screen Shot 2021-05-26 at 7 24 30 PM](https://user-images.githubusercontent.com/28850131/119743677-6670cc80-be58-11eb-8726-42a2d8073556.png)
![Screen Shot 2021-05-26 at 7 24 20 PM](https://user-images.githubusercontent.com/28850131/119743682-68d32680-be58-11eb-896c-dfd664ef0aee.png)

**Comment by bendhouseart** [comment]
Created a PR w/ Greg's fix, which fixes some of the issues I was seeing on chrome and safari on the other two sets of banner buttons. The original bug still persists.......PR is marked as draft until then.
